TERMINAL LIST
Type:      File
Name:      f1
Original:  <dir>/r4/f1
Created:   2020-05-31 12:00:00 
Entries:      1
Total Files:  1
Log size:     0.00B
Size:         5.00B 


EXCEPTION RESTORE
Exceptions:

- Cannot restore the trash file 'f1' as one exists at the original location: <dir>/r4/f1

CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:0:0 in <package>:SafeRm.Effects.MonadCallStack
  throwCallStack, called at src/SafeRm/Data/PathData.hs:0:0 in <package>:SafeRm.Data.PathData
  mvTrashToOriginal, called at src/SafeRm.hs:0:0 in <package>:SafeRm
  restore, called at src/SafeRm/Runner.hs:0:0 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:0:0 in <package>:Functional.Prelude

LOGS RESTORE
[2020-05-31 12:00:00][functional.restore][Debug][src/SafeRm.hs] Trash home: <dir>/r4/.trash
[2020-05-31 12:00:00][functional.restore.readIndex][Debug][src/SafeRm/Data/Index.hs] Index path: <dir>/r4/.trash/.index.csv
[2020-05-31 12:00:00][functional.restore.readIndex.readIndexWithFold][Debug][src/SafeRm/Data/Index.hs] Found: MkPathData {pathType = PathTypeFile, fileName = MkPathI {unPathI = "f1"}, originalPath = MkPathI {unPathI = "<dir>/r4/f1"}, created = MkTimestamp {unTimestamp = 2020-05-31 12:00:00}}
[2020-05-31 12:00:00][functional.restore.restoring][Debug][src/SafeRm.hs] MkPathData {pathType = PathTypeFile, fileName = MkPathI {unPathI = "f1"}, originalPath = MkPathI {unPathI = "<dir>/r4/f1"}, created = MkTimestamp {unTimestamp = 2020-05-31 12:00:00}}
[2020-05-31 12:00:00][functional.restore.restoring][Warn][src/SafeRm.hs] Cannot restore the trash file 'f1' as one exists at the original location: <dir>/r4/f1

CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:0:0 in <package>:SafeRm.Effects.MonadCallStack
  throwCallStack, called at src/SafeRm/Data/PathData.hs:0:0 in <package>:SafeRm.Data.PathData
  mvTrashToOriginal, called at src/SafeRm.hs:0:0 in <package>:SafeRm
  restore, called at src/SafeRm/Runner.hs:0:0 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:0:0 in <package>:Functional.Prelude
[2020-05-31 12:00:00][functional.restore][Info][src/SafeRm.hs] Restored: 
[2020-05-31 12:00:00][functional][Error][src/SafeRm/Runner.hs] Exceptions:

- Cannot restore the trash file 'f1' as one exists at the original location: <dir>/r4/f1

CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:0:0 in <package>:SafeRm.Effects.MonadCallStack
  throwCallStack, called at src/SafeRm/Data/PathData.hs:0:0 in <package>:SafeRm.Data.PathData
  mvTrashToOriginal, called at src/SafeRm.hs:0:0 in <package>:SafeRm
  restore, called at src/SafeRm/Runner.hs:0:0 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:0:0 in <package>:Functional.Prelude
